[package]
name = "brize"
version = "0.1.0"
edition = "2021"
authors=["Jonathan Karrer <karrerjon@gmail.com>"]
description = "Minimalistic Rust Framework"
license = "MIT/Apache-2.0"
repository = "https://github.com/jonkarrer/brize"
readme = "README.md"
keywords = ["framework"]
categories = ["software"]


[dependencies]
