[package]
name = "setup"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
publish = false

[dependencies]
config = { workspace = true }
diesel = { workspace = true }
bcrypt = { workspace = true }
colored = "3.0.0"
dialoguer = "0.11.0" 
uuid = { version = "1.17.0", features = ["v4"] }
